import type { GapTask, Sentence, TopicId, Word, Zone } from "./types";

const W = (topic: TopicId, lvl: 1 | 2 | 3, en: string, ru: string): Word => ({
  id: `${topic}-${en.toLowerCase().replace(/[^a-z]+/g, "")}`,
  en,
  ru,
  topic,
  lvl,
});

export const TOPIC_NAMES: Record<TopicId, string> = {
  greet: "Приветствия",
  animals: "Животные",
  food: "Еда",
  colors: "Цвета и числа",
  family: "Семья и дом",
  actions: "Действия",
};

export const WORDS: Word[] = [
  W("greet", 1, "hello", "привет"),
  W("greet", 1, "goodbye", "пока"),
  W("greet", 1, "please", "пожалуйста"),
  W("greet", 1, "thank you", "спасибо"),
  W("greet", 1, "sorry", "извини"),
  W("greet", 1, "yes", "да"),
  W("greet", 1, "no", "нет"),
  W("greet", 1, "friend", "друг"),
  W("greet", 2, "good morning", "доброе утро"),
  W("greet", 2, "good night", "спокойной ночи"),
  W("greet", 2, "how are you", "как дела"),
  W("greet", 3, "nice to meet you", "приятно познакомиться"),
  W("animals", 1, "cat", "кот"),
  W("animals", 1, "dog", "собака"),
  W("animals", 1, "fish", "рыба"),
  W("animals", 1, "bird", "птица"),
  W("animals", 1, "lion", "лев"),
  W("animals", 1, "tiger", "тигр"),
  W("animals", 1, "bear", "медведь"),
  W("animals", 1, "monkey", "обезьяна"),
  W("animals", 2, "elephant", "слон"),
  W("animals", 2, "rabbit", "кролик"),
  W("animals", 2, "horse", "лошадь"),
  W("animals", 2, "frog", "лягушка"),
  W("animals", 2, "fox", "лиса"),
  W("animals", 2, "snake", "змея"),
  W("animals", 3, "shark", "акула"),
  W("animals", 3, "dolphin", "дельфин"),
  W("food", 1, "apple", "яблоко"),
  W("food", 1, "banana", "банан"),
  W("food", 1, "milk", "молоко"),
  W("food", 1, "bread", "хлеб"),
  W("food", 1, "cheese", "сыр"),
  W("food", 1, "egg", "яйцо"),
  W("food", 1, "juice", "сок"),
  W("food", 1, "pizza", "пицца"),
  W("food", 2, "cake", "торт"),
  W("food", 2, "ice cream", "мороженое"),
  W("food", 2, "carrot", "морковь"),
  W("food", 2, "tomato", "помидор"),
  W("food", 2, "chicken", "курица"),
  W("food", 2, "water", "вода"),
  W("food", 3, "cookie", "печенье"),
  W("food", 3, "sandwich", "бутерброд"),
  W("colors", 1, "red", "красный"),
  W("colors", 1, "blue", "синий"),
  W("colors", 1, "green", "зелёный"),
  W("colors", 1, "yellow", "жёлтый"),
  W("colors", 1, "black", "чёрный"),
  W("colors", 1, "white", "белый"),
  W("colors", 2, "orange", "оранжевый"),
  W("colors", 2, "purple", "фиолетовый"),
  W("colors", 2, "pink", "розовый"),
  W("colors", 2, "one", "один"),
  W("colors", 2, "two", "два"),
  W("colors", 2, "three", "три"),
  W("colors", 2, "four", "четыре"),
  W("colors", 2, "five", "пять"),
  W("colors", 3, "six", "шесть"),
  W("colors", 3, "seven", "семь"),
  W("colors", 3, "eight", "восемь"),
  W("colors", 3, "nine", "девять"),
  W("colors", 3, "ten", "десять"),
  W("colors", 3, "twenty", "двадцать"),
  W("family", 1, "mother", "мама"),
  W("family", 1, "father", "папа"),
  W("family", 1, "brother", "брат"),
  W("family", 1, "sister", "сестра"),
  W("family", 1, "grandmother", "бабушка"),
  W("family", 1, "grandfather", "дедушка"),
  W("family", 1, "child", "ребёнок"),
  W("family", 1, "family", "семья"),
  W("family", 2, "house", "дом"),
  W("family", 2, "room", "комната"),
  W("family", 2, "bed", "кровать"),
  W("family", 2, "table", "стол"),
  W("family", 2, "chair", "стул"),
  W("family", 2, "door", "дверь"),
  W("family", 3, "window", "окно"),
  W("family", 3, "garden", "сад"),
  W("actions", 1, "run", "бегать"),
  W("actions", 1, "jump", "прыгать"),
  W("actions", 1, "swim", "плавать"),
  W("actions", 1, "fly", "летать"),
  W("actions", 1, "read", "читать"),
  W("actions", 1, "write", "писать"),
  W("actions", 1, "sing", "петь"),
  W("actions", 1, "dance", "танцевать"),
  W("actions", 2, "play", "играть"),
  W("actions", 2, "eat", "есть, кушать"),
  W("actions", 2, "drink", "пить"),
  W("actions", 2, "sleep", "спать"),
  W("actions", 2, "draw", "рисовать"),
  W("actions", 2, "climb", "карабкаться"),
  W("actions", 3, "throw", "бросать"),
  W("actions", 3, "catch", "ловить"),
];

export const WORD_BY_ID: Record<string, Word> = Object.fromEntries(WORDS.map((w) => [w.id, w]));
export const WORDS_BY_TOPIC = (t: TopicId) => WORDS.filter((w) => w.topic === t);

export const DICT_EN: Record<string, Word> = Object.fromEntries(WORDS.map((w) => [w.en.toLowerCase(), w]));
export const DICT_RU: Record<string, Word> = Object.fromEntries(WORDS.map((w) => [w.ru.toLowerCase(), w]));

export const ZONES: Zone[] = [
  { id: "greet", title: "Планета Приветствий", subtitle: "Первые слова героя", reqLevel: 1, hue: "#00e5ff", hue2: "#4d7cff", ring: false, quests: [{ id: "greet-1", zone: "greet", title: "Разведка", kind: "lesson", steps: 8 }, { id: "greet-2", zone: "greet", title: "Тайный сигнал", kind: "lesson", steps: 10 }, { id: "greet-3", zone: "greet", title: "Босс: Глитч", kind: "boss", steps: 10 }] },
  { id: "animals", title: "Остров Зверей", subtitle: "Дикие союзники", reqLevel: 2, hue: "#a3ff12", hue2: "#22c55e", ring: false, quests: [{ id: "animals-1", zone: "animals", title: "Следы на песке", kind: "lesson", steps: 9 }, { id: "animals-2", zone: "animals", title: "Ночной дозор", kind: "lesson", steps: 10 }, { id: "animals-3", zone: "animals", title: "Босс: Краб-Командор", kind: "boss", steps: 11 }] },
  { id: "food", title: "Лагуна Вкусняшек", subtitle: "Энергия для героя", reqLevel: 3, hue: "#ffd60a", hue2: "#ff9f0a", ring: true, quests: [{ id: "food-1", zone: "food", title: "Пикник разведчика", kind: "lesson", steps: 9 }, { id: "food-2", zone: "food", title: "Кухня капитана", kind: "lesson", steps: 10 }, { id: "food-3", zone: "food", title: "Босс: Желейный Титан", kind: "boss", steps: 11 }] },
  { id: "colors", title: "Город Цвета и Чисел", subtitle: "Код неоновых огней", reqLevel: 4, hue: "#ff2ec4", hue2: "#ff5470", ring: true, quests: [{ id: "colors-1", zone: "colors", title: "Огни города", kind: "lesson", steps: 9 }, { id: "colors-2", zone: "colors", title: "Шифр чисел", kind: "lesson", steps: 10 }, { id: "colors-3", zone: "colors", title: "Босс: Пиксель-Фантом", kind: "boss", steps: 12 }] },
  { id: "family", title: "Замок Семьи", subtitle: "Команда героя", reqLevel: 5, hue: "#8b5cf6", hue2: "#c084fc", ring: false, quests: [{ id: "family-1", zone: "family", title: "Жители замка", kind: "lesson", steps: 9 }, { id: "family-2", zone: "family", title: "Карта комнат", kind: "lesson", steps: 10 }, { id: "family-3", zone: "family", title: "Босс: Теневой Рыцарь", kind: "boss", steps: 12 }] },
  { id: "actions", title: "Арена Действий", subtitle: "Суперспособности", reqLevel: 6, hue: "#00e5ff", hue2: "#ff2ec4", ring: true, quests: [{ id: "actions-1", zone: "actions", title: "Тренировка героев", kind: "lesson", steps: 9 }, { id: "actions-2", zone: "actions", title: "Полоса препятствий", kind: "lesson", steps: 10 }, { id: "actions-3", zone: "actions", title: "Босс: Нео-Дракон", kind: "boss", steps: 12 }] },
];

export const SENTENCES: Sentence[] = [
  { id: "s1", en: "I like pizza", ru: "Я люблю пиццу", topic: "food", lvl: 1, tokens: ["I", "like", "pizza"], distractor: "run" },
  { id: "s2", en: "The cat is black", ru: "Кот чёрный", topic: "colors", lvl: 1, tokens: ["The", "cat", "is", "black"], distractor: "juice" },
  { id: "s3", en: "I can jump high", ru: "Я умею прыгать высоко", topic: "actions", lvl: 1, tokens: ["I", "can", "jump", "high"], distractor: "milk" },
  { id: "s4", en: "She is my sister", ru: "Она моя сестра", topic: "family", lvl: 1, tokens: ["She", "is", "my", "sister"], distractor: "apple" },
  { id: "s5", en: "The fish can swim", ru: "Рыба умеет плавать", topic: "animals", lvl: 1, tokens: ["The", "fish", "can", "swim"], distractor: "bread" },
  { id: "s6", en: "I see a red bird", ru: "Я вижу красную птицу", topic: "colors", lvl: 1, tokens: ["I", "see", "a", "red", "bird"], distractor: "sleep" },
  { id: "s7", en: "We play football", ru: "Мы играем в футбол", topic: "actions", lvl: 2, tokens: ["We", "play", "football"], distractor: "chair" },
  { id: "s8", en: "I have two brothers", ru: "У меня два брата", topic: "family", lvl: 2, tokens: ["I", "have", "two", "brothers"], distractor: "swim" },
  { id: "s9", en: "My mother is kind", ru: "Моя мама добрая", topic: "family", lvl: 2, tokens: ["My", "mother", "is", "kind"], distractor: "tiger" },
  { id: "s10", en: "He runs fast", ru: "Он бегает быстро", topic: "actions", lvl: 2, tokens: ["He", "runs", "fast"], distractor: "cake" },
  { id: "s11", en: "I drink apple juice", ru: "Я пью яблочный сок", topic: "food", lvl: 2, tokens: ["I", "drink", "apple", "juice"], distractor: "door" },
  { id: "s12", en: "The dog likes milk", ru: "Собака любит молоко", topic: "animals", lvl: 2, tokens: ["The", "dog", "likes", "milk"], distractor: "ten" },
];

export const GAP_TASKS: GapTask[] = [
  { id: "g1", before: "I", after: "a dog.", options: ["have", "has", "is"], answer: "have", hint: "С местоимениями I / you / we / they — have.", topic: "family", lvl: 1 },
  { id: "g2", before: "She", after: "ten.", options: ["am", "is", "are"], answer: "is", hint: "He / She / It дружит с is.", topic: "colors", lvl: 1 },
  { id: "g3", before: "They", after: "in the sea.", options: ["swim", "swims", "swimming"], answer: "swim", hint: "They / We — глагол без изменений.", topic: "animals", lvl: 1 },
  { id: "g4", before: "I can", after: "fast.", options: ["run", "runs", "running"], answer: "run", hint: "После can глагол без окончаний.", topic: "actions", lvl: 1 },
  { id: "g5", before: "The elephant", after: "big.", options: ["is", "are", "am"], answer: "is", hint: "Один слон — значит is.", topic: "animals", lvl: 1 },
  { id: "g6", before: "We", after: "pizza every day.", options: ["like", "likes", "liking"], answer: "like", hint: "We — like без s.", topic: "food", lvl: 2 },
  { id: "g7", before: "He", after: "a big house.", options: ["has", "have", "is"], answer: "has", hint: "He / She — has.", topic: "family", lvl: 2 },
  { id: "g8", before: "", after: "you like bananas?", options: ["Do", "Does", "Is"], answer: "Do", hint: "С you в вопросах работает Do.", topic: "food", lvl: 2 },
  { id: "g9", before: "I have three", after: ".", options: ["cats", "cat", "a cat"], answer: "cats", hint: "После чисел — множественное число: cats.", topic: "animals", lvl: 2 },
  { id: "g10", before: "She can't", after: ".", options: ["fly", "flies", "flying"], answer: "fly", hint: "После can't — глагол без окончаний.", topic: "actions", lvl: 2 },
  { id: "g11", before: "", after: "is my friend.", options: ["He", "Him", "His"], answer: "He", hint: "Кто? — He. В начале предложения.", topic: "greet", lvl: 3 },
  { id: "g12", before: "My father", after: "to work.", options: ["goes", "go", "going"], answer: "goes", hint: "My father = he → goes с окончанием -es.", topic: "family", lvl: 3 },
];

export const PLACEMENT: { ru: string; options: string[]; answer: string; wordId: string }[] = [
  { ru: "кот", options: ["cat", "dog", "fish"], answer: "cat", wordId: "animals-cat" },
  { ru: "яблоко", options: ["milk", "apple", "bread"], answer: "apple", wordId: "food-apple" },
  { ru: "красный", options: ["red", "green", "blue"], answer: "red", wordId: "colors-red" },
  { ru: "бегать", options: ["sleep", "run", "swim"], answer: "run", wordId: "actions-run" },
  { ru: "мама", options: ["father", "mother", "child"], answer: "mother", wordId: "family-mother" },
  { ru: "собака", options: ["bird", "dog", "cat"], answer: "dog", wordId: "animals-dog" },
];

export const ACHIEVEMENTS: { id: string; name: string; desc: string }[] = [
  { id: "first", name: "Первый шаг", desc: "Пройди первый квест" },
  { id: "trio", name: "Разогрев", desc: "Пройди 3 квеста" },
  { id: "ten", name: "Десяточка", desc: "Пройди 10 квестов" },
  { id: "lvl3", name: "Новичок+", desc: "Достигни 3 уровня" },
  { id: "lvl5", name: "Бывалый герой", desc: "Достигни 5 уровня" },
  { id: "streak3", name: "Три дня подряд", desc: "Серия из 3 дней" },
  { id: "words25", name: "Живой словарь", desc: "Выучи 25 слов крепко" },
  { id: "boss1", name: "Гроза боссов", desc: "Победи первого босса" },
  { id: "bossall", name: "Чемпион галактики", desc: "Победи всех 6 боссов" },
  { id: "voice10", name: "Голос героя", desc: "Произнеси 10 слов в микрофон" },
  { id: "perfect", name: "Без единой ошибки", desc: "Пройди квест на 100%" },
];

export const GRAMMAR_TIPS: { title: string; text: string }[] = [
  { title: "am / is / are", text: "I → am, he/she/it → is, you/we/they → are. Пример: I am ten. She is my sister. We are friends." },
  { title: "have / has", text: "I/you/we/they → have, he/she/it → has. Пример: I have a dog. He has two cats." },
  { title: "can — умею", text: "После can глагол без окончаний: I can run. She can't fly. Can you swim?" },
  { title: "Множественное число", text: "Один cat — два cats. К слову добавляем -s: three apples, ten birds." },
  { title: "like / likes", text: "I/you/we/they → like, he/she/it → likes. Пример: I like pizza. My mother likes tea." },
];

export const VOLT_PRAISE = ["Мощно! Ты заряжен на 100%!", "Вот это точность! Так держать, герой!", "Нейроны сверкают! Верно!", "Ты взломал этот код!", "Супер! Даже боссы дрожат!", "Идеальный выстрел!"];
export const VOLT_OOPS = ["Ой! Ничего, ошибка — это топливо для ума!", "Почти! Запомни правильный ответ — и вперёд!", "Босс хихикает, но мы его перехитрим!", "Сбой в матрице! Смотри, как правильно.", "Не попал — зато теперь точно запомнишь!"];

export const VOLT_INTRO_LINES: Record<string, string> = {
  intro: "Новое слово! Посмотри, послушай и нажми «Запомнил».",
  listenChoice: "Включаю звук! Выбери правильный перевод.",
  ruToEn: "Как это будет по-английски? Выбери верный вариант!",
  enToRu: "Что значит это слово? Жми на перевод!",
  spell: "Буквы перепутаны! Собери слово по буквам.",
  match: "Соедини пары: английский — русский!",
  build: "Собери предложение из слов по порядку!",
  gap: "В предложении пропуск. Какое слово подойдёт?",
  speak: "Прослушай слово и повтори его в микрофон!",
};
